
# Dockerfile
FROM php:7.4.3-cli
# Install Composer
RUN apt-get update -y && apt-get install -y openssl zip unzip git
COPY --from=composer /usr/bin/composer /usr/bin/composer
RUN docker-php-ext-install pdo pdo_mysql
WORKDIR /app
COPY . /app

EXPOSE 8080

#RUN php artisan make:migration create_employees_table
#RUN php artisan migrate

#RUN php artisan make:SQLSTATE[HY000] [2002] Connection refused controller EmployeeController
#RUN php artisan make:model Employee
RUN php artisan config:clear

CMD php artisan serve --host=0.0.0.0 --port=8080